---
apiVersion: v1
kind: Pod
metadata:
  name: node-labeler
spec:
  containers:
  - name: node-labeler
    image: quay.io/mboersma/node-labeler:latest
    imagePullPolicy: Always
  serviceAccountName: monitor-nodes-serviceaccount
