---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-nodes-serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-nodes
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-nodes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-nodes
subjects:
  - kind: ServiceAccount
    name: monitor-nodes-serviceaccount
    namespace: example-monitor-nodes
