---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: quay.io/mboersma/shell-operator:monitor-nodes
    imagePullPolicy: Always
  serviceAccountName: monitor-nodes-serviceaccount
